name: CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # Replace with your Docker Hub or ECR repository
  DOCKER_REPO_BACKEND: your-dockerhub-username/producer-matching-backend
  DOCKER_REPO_FRONTEND: your-dockerhub-username/producer-matching-frontend

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push backend image
        run: |
          docker build -t ${{ env.DOCKER_REPO_BACKEND }}:latest ./backend
          docker push ${{ env.DOCKER_REPO_BACKEND }}:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.DOCKER_REPO_FRONTEND }}:latest ./frontend
          docker push ${{ env.DOCKER_REPO_FRONTEND }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    environment: production # Optional: for environment protection
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/app # Change to your application directory on the server
            docker compose pull
            docker compose up -d --build # --build to ensure latest images are used
            # Or, if you have a more complex deployment script, call it here
